// team-guide.mjs - render the member-facing field manual (guide.md) and the short
// bootstrap trigger a member Agent reads on dispatch. Pure string builders, no I/O.
//
// LazyZ port: ZCode has no Codex threads. A member is a one-shot Agent-tool call
// whose FINAL MESSAGE is the deliverable. There is no live `send_message_to_thread`;
// members report by returning their findings in their final message and exchange
// files through the shared artifacts/ directory. The guide reflects this model.

function memberLine(member) {
	const wt = member.worktree?.path ? ` | worktree ${member.worktree.path}` : "";
	const run = member.runId ? ` | run ${member.runId}` : "";
	const name = member.name ? ` "${member.name}"` : "";
	return `- **${member.id}**${name} (${member.lens}) - ${member.focus}${member.deliverable ? ` -> ${member.deliverable}` : ""}${run}${wt} [${member.status}]`;
}

function worktreeSection(team) {
	if (!team.worktree?.enabled) {
		return `## Worktrees

This team does not use isolated git worktrees. Work in the shared repository checkout
the leader is running from. If your changes would collide with another member's files,
that is a coordination signal: report \`BLOCKED: <reason>\` in your final message to the leader.`;
	}
	const lines = team.members
		.filter((m) => m.worktree?.path || m.worktree?.branch)
		.map((m) => {
			return `- **${m.id}**: worktree \`${m.worktree.path ?? "(assign via worktree-add)"}\` on branch \`${m.worktree.branch ?? team.worktree.baseBranch}\``;
		});
	return `## Worktrees (ISOLATION IS ON - this is not optional for you)

This team runs each member in its own git worktree branched off \`${team.worktree.baseBranch}\`.
**You MUST work only inside your own worktree.** The leader passes your worktree path in
your dispatch prompt; every edit, command, and commit happens there. Never touch another
member's worktree, and never edit files outside your assigned scope. Commit your work so the
leader can integrate it. If your assigned worktree path is missing, empty, or does not look
like a git worktree/repository, report \`BLOCKED: worktree not ready\` in your final message
and stop.

${lines.length ? lines.join("\n") : "- (worktree paths are assigned as members are dispatched; read team.json for yours)"}`;
}

export function buildGuide(team) {
	const artifacts = team.paths?.artifacts ?? ".omo/teams/<session_id>/artifacts";
	const teamJson = team.paths?.team ?? ".omo/teams/<session_id>/team.json";
	const roster = team.members.length ? team.members.map(memberLine).join("\n") : "- (no members yet)";
	return `# Team ${team.teamName} - Member Field Manual

> Auto-generated by the LazyZ teammode script. This file is the single source of truth for
> how this team works. The leader embeds it (or a pointer to it) in your dispatch prompt.
> Re-read it whenever you are unsure - do not improvise the protocol.

- Team: **${team.teamName}** (id \`${team.teamId}\`)
- Team state: \`${teamJson}\`

## Who you are (your identity is fixed)

**You are a member of team ${team.teamName}, not a generic assistant.** You own exactly one
slice of this team's work - the focus and deliverable assigned to your id below - and you are
accountable for it end to end. Read your row, internalize it, and act as that owner for the
whole dispatch. Do not drift into other members' scope.

${roster}

## Leader

**The main session is the leader. There is no other leader, and you are not it.** You report
to the leader and take direction from the leader. The leader owns the final decision and
integration. You do not integrate other members' work.

## Communication model (ZCode Agent-tool - READ CAREFULLY)

You are a **one-shot dispatch**: the leader called you through the ZCode \`Agent\` tool with a
self-contained prompt. You have **one turn** to do your work and return your result. There is
no live messaging channel to the leader or peers mid-run. Everything you need to say must be
in your **final message** back to the leader.

- **All communication in your final message is in English**, regardless of the language the
  task was given in. (Exception: if the END USER addresses you directly through the leader,
  the leader relays in the user's language; you still report to the leader in English.)
- **Your final message is your deliverable.** Structure it so the leader can act on it:
  - Lead with a one-line status: \`DONE: <deliverable>\`, \`BLOCKED: <reason>\`, or \`PARTIAL: <what is done> / <what remains>\`.
  - Then: the key findings, the files you changed (paths), the commands you ran and their
    results, and any evidence the work is correct (test output, screenshots, logs).
  - End with a short \`NEXT:\` line of the single most useful follow-up, or \`NONE\` if the slice
    is genuinely complete.
- **Exchange large artifacts through the team artifacts directory** (not by pasting huge
  content into your final message): \`${artifacts}\`. Write files there (diffs, notes, reports)
  and reference them by path in your message.
- **If you depend on a peer's output that is not yet available**, do not block silently: check
  \`${artifacts}\` for their deliverable; if absent, return \`BLOCKED: waiting on <member id> for <thing>\`
  so the leader can re-sequence.

## Artifacts (how you hand work off)

Exchange files and memos through the team artifacts directory:

\`${artifacts}\`

Drop deliverables, notes, diffs, and findings there as files, and reference them by path in
your final message instead of pasting large content. Treat it as the team's shared desk: if a
peer or the leader needs something from you, leave it in artifacts and point them to it.

${worktreeSection(team)}

## Done means reported and verified

Your slice is done only when (1) the deliverable exists, (2) you have evidence it works, and
(3) your final message reports it to the leader with the \`DONE:\` status line. Until all three
are true, keep working within your turn.`;
}

export function buildMemberPrompt(team, id) {
	const member = team.members.find((m) => m.id === id);
	if (!member) throw new Error(`no member with id "${id}"`);
	const guide = team.paths?.guide ?? ".omo/teams/<session_id>/guide.md";
	const teamJson = team.paths?.team ?? ".omo/teams/<session_id>/team.json";
	const where = member.cwd
		? `Work inside \`${member.cwd}\` (your assigned worktree).`
		: team.worktree?.enabled
			? "Your worktree path is not assigned yet; report BLOCKED if the leader dispatched you without one."
			: "Work from the repository root unless your manual assigns a worktree.";
	const readiness =
		team.worktree?.enabled
			? "\nBefore editing, verify that your assigned worktree exists and contains repo files. If the path is missing, empty, or not a git worktree/repository, return `BLOCKED: worktree not ready` and stop."
			: "";
	return `You are member ${member.id}${member.name ? ` (${member.name})` : ""} of team ${team.teamName} - owner of: ${member.focus}. Your deliverable: ${member.deliverable || "(not specified - infer from your focus)"}.
FIRST read your field manual at \`${guide}\`, then the team state at \`${teamJson}\`; they define your scope, deliverable, the leader, the artifacts directory, and the communication model.
${where}${readiness}
You have ONE turn. Do the work, then return your deliverable to the leader in your final message, structured per the guide (status line first: DONE/BLOCKED/PARTIAL). Put large outputs in the artifacts directory and reference them by path. Report in English.`;
}
